### PR TITLE
Added trajectories within trips to map, fixed local dates/times, added functionality to add some and hide other columns.

### PR DESCRIPTION
**Pull request by ahcyip**
Query recreated_locations, join them to trips, and create trajectories within trips for plotting. Fix datetimes to show local times. Add columns for min, mi, km. Remove specific unnecessary columns in tables, map filter, and map popups.

As requested by @shankari

### CODE REVIEW

**Comment by ahcyip** [comment]
We also wanted to separate the query for locations and the creation of trajectories depending on the map filters, but I ran out of time to implement this. With sample test data, it doesn't matter too much, but with large numbers of locations per trip per user, this could be unnecessary bogging down of the dashboard. I think we could wait for equisse:filterDF to generate trips_filtered and then query locations and join trajectories at that point. (ran out of time to implement this) @shankari

**Comment by shankari** [comment]
@ahcyip "remove" == "hide", right?

**Comment by ahcyip** [comment]
yes, hides from final display, but still in the data table

**Comment by asiripanich** [comment]
@ahcyip it is not working on my machine. Does it work on yours? I need to look at it more next week to understand why it is not working.

**Comment by ahcyip** [comment]
oops, I closed by accident. 
@asiripanich I did encounter this 
`Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'PopupTable-0.0.1'; `directoryPath` = ''`
I resolved it by `remotes::install_github("r-spatial/mapview")` as suggested in https://github.com/r-spatial/mapview/issues/312

**Comment by ahcyip** [comment]
hmm, I may not have fully tested the last few changes to do with hiding columns. The trajectories and dates worked. I'll try to fix it before next week.

**Comment by asiripanich** [comment]
I'm seeing a different error, but it is not very informative that I can quickly debug it. Will carefully review this next week. 

```r
> run_app()

Listening on http://127.0.0.1:5967
Running: mod_load_data_server
About to load trips
Finished query, about to clean trips
Finished cleaning trips
Finished loading trips
About to load locations
Finished query, about to clean locations
Finished cleaning locations
Finished loading locations
About to create trajectories within trips
About to generate trajectories
Trajectories created
Finished creating trajectories within trips
About to load participants
Finished loading participants
Called from: (function (e) 
{
    if (inherits(e, "shiny.silent.error")) 
        return()
    handle <- getOption("shiny.error")
    if (is.function(handle)) 
        handle()
})(list(message = "cannot coerce type 'closure' to vector of type 'any'", 
    call = as.vector(x, mode)))
```

**Comment by ahcyip** [comment]
Yes, now I'm seeing `Warning: Error in as.vector: cannot coerce type 'closure' to vector of type 'any'` too. 
and I had to add a `reactive()` in app_server too.

**Comment by ahcyip** [comment]
OK I pushed a few changes that I think should fix it, but I don't have the mongodb to test it. Hope it works - and if not, I'll revisit it next week (if you don't figure it out first @asiripanich )

**Comment by ahcyip** [comment]
Tested and tweaked again and now it works! at least for me. lol. @asiripanich Hope it works for your mongodb and test data too.

**Comment by shankari** [comment]
@asiripanich just a note on the time changes. I believe you were initially wrapping the times in lubridate, which parses them into UTC by default. This has two problems:
- the trip start/end in the dashboard is off by multiple hours, so it looks like people are taking trips in the middle of the night, and
- the per day trip histogram doesn't accurately reflect travel. In both AU and US, travel on a holiday will be split between two different UTC days, so we won't be able to see "special" behavior

Maybe these are not that important for travel diaries, but I do think that they are important in general. To address this, I believe,
- we use the original `*_fmt_time` which is already formatted in the local timezone for display
- we use the `*_local_dt` structure which has the components in the local timezone for grouping
- we use the lubridate in the time range sliders on the map page for trip selection because none of the other approaches works well for a range

**Review by asiripanich — COMMENTED** [review]
fixed the missing reactive context.

**Comment by asiripanich** [comment]
> @asiripanich just a note on the time changes. I believe you were initially wrapping the times in lubridate, which parses them into UTC by default. This has two problems:
> 
>     * the trip start/end in the dashboard is off by multiple hours, so it looks like people are taking trips in the middle of the night, and
> 
>     * the per day trip histogram doesn't accurately reflect travel. In both AU and US, travel on a holiday will be split between two different UTC days, so we won't be able to see "special" behavior
> 
> 
> Maybe these are not that important for travel diaries, but I do think that they are important in general. To address this, I believe,
> 
>     * we use the original `*_fmt_time` which is already formatted in the local timezone for display
> 
>     * we use the `*_local_dt` structure which has the components in the local timezone for grouping
> 
>     * we use the lubridate in the time range sliders on the map page for trip selection because none of the other approaches works well for a range

@shankari, I vaguely remember there was that it was an issue for me as well, but did not bother to fix it because I was using it alone. I do agree with your proposed solutions. Happy to review and test if you can send in a draft PR.

**Comment by asiripanich** [comment]
> Tested and tweaked again and now it works! at least for me. lol. @asiripanich Hope it works for your mongodb and test data too.

works perfectly. ;) 

However, I think there should be a cleaner way to include all those variables that you want to remove.

**Comment by shankari** [comment]
@asiripanich 

> Happy to review and test if you can send in a draft PR.

I believe those changes are included in this PR by @ahcyip 😄

**Comment by ahcyip** [comment]
> @asiripanich
> 
> > Happy to review and test if you can send in a draft PR.
> 
> I believe those changes are included in this PR by @ahcyip 😄

Yes, sorry, a large commit with all the changes - I should have done it piece by piece. 

I added a start_local_time and end_local_time in string format, because R cannot have a column of datetime type with different time zones. These local times are sortable in the tables so I display those. They're not filterable for the map (so I left the map filter using the UTC time) but the map popups display the local times.

**Comment by asiripanich** [comment]
> > @asiripanich
> > > Happy to review and test if you can send in a draft PR.
> > 
> > 
> > I believe those changes are included in this PR by @ahcyip 😄
> 
> Yes, sorry, a large commit with all the changes - I should have done it piece by piece.
> 
> I added a start_local_time and end_local_time in string format, because R cannot have a column of datetime type with different time zones. These local times are sortable in the tables so I display those. They're not filterable for the map (so I left the map filter using the UTC time) but the map popups display the local times.

@ahcyip Could you please check if the map's filter works correctly with your changes? Filter by duration and distance don't seem to work for me.

**Comment by ahcyip** [comment]
> > > @asiripanich
> > > > Happy to review and test if you can send in a draft PR.
> > > 
> > > 
> > > I believe those changes are included in this PR by @ahcyip 😄
> > 
> > 
> > Yes, sorry, a large commit with all the changes - I should have done it piece by piece.
> > I added a start_local_time and end_local_time in string format, because R cannot have a column of datetime type with different time zones. These local times are sortable in the tables so I display those. They're not filterable for the map (so I left the map filter using the UTC time) but the map popups display the local times.
> 
> @ahcyip Could you please check if the map's filter works correctly with your changes? Filter by duration and distance don't seem to work for me.

Yes, I just tested it and the map filters work for me. Noticed a minor thing wrong with the timestamp (added the wrong time zone) so I fixed that.
Are your durations and distances NAs? I noticed that trips with NA distance or duration showed by default. Maybe a setting to change in equisse::filterDT.

**Comment by asiripanich** [comment]
> > > > @asiripanich
> > > > > Happy to review and test if you can send in a draft PR.
> > > > 
> > > > 
> > > > I believe those changes are included in this PR by @ahcyip 😄
> > > 
> > > 
> > > Yes, sorry, a large commit with all the changes - I should have done it piece by piece.
> > > I added a start_local_time and end_local_time in string format, because R cannot have a column of datetime type with different time zones. These local times are sortable in the tables so I display those. They're not filterable for the map (so I left the map filter using the UTC time) but the map popups display the local times.
> > 
> > 
> > @ahcyip Could you please check if the map's filter works correctly with your changes? Filter by duration and distance don't seem to work for me.
> 
> Yes, I just tested it and the map filters work for me. Noticed a minor thing wrong with the timestamp (added the wrong time zone) so I fixed that.
> Are your durations and distances NAs? I noticed that trips with NA distance or duration showed by default. Maybe a setting to change in equisse::filterDT.

I see. @ahcyip Could you please see NEWS.md and add the changes you have implemented. Then I will merge this PR. ;)

**Comment by ahcyip** [comment]
Cool! Thanks for your support and accepting my contributions to open source... and I learned a few things about R datetimes, GIS simple features, Shiny, Golem, roxygen2, equisse, DT::datatable ... ...

**Comment by ahcyip** [comment]
I just learned about `reactlog` which would have helped me debug this faster! So much Shiny to learn!

**Comment by asiripanich** [comment]
@ahcyip thanks for sharing. I will check that out as well. 

At some point, we should add unit tests to emdash. So much to learn.. ;)

**Pull request merged**
