### PR TITLE
Changed the tables section column names and tag font size

### PR DESCRIPTION
**Pull request by allenmichael099**
In app_server:
Changed the displayed column names so that they are easier to understand.
Used setnames within observeEvent for the esquisse plots and for the data table.

In app_ui:
changed the font size for the variable tags within box() after esquisserUI was called

### CODE REVIEW

**Comment by asiripanich** [comment]
@allenmichael099 Thank you for the PR I will try to review it by today.

**Comment by asiripanich** [comment]
@allenmichael099 would you mind creating a draft PR of the branch that you are working on the config file as well? as a separate PR.

**Comment by asiripanich** [comment]
Hi @allenmichael099, instead of hard coding the label names, should we use the config file that you are working on to do that?

Also, when you make UI changes to the dashboard, I think it is a good idea to post screenshots of before and after, so that who ever reviews it knows exactly what to look for.

**Comment by allenmichael099** [comment]
@asiripanich I now have a draft PR for the YAML config file and pictures of UI changes to go along with that PR. I went with your suggestion to move the label names into the config file. I also realized that my label size for the plot may be the same as or very similar to the original label size. I think I will increase it to 14 instead of 12. 

image

**Comment by asiripanich** [comment]
Let's address these in #32.

**Pull request closed without merging**
