### PR TITLE
Display user labels generically in the dashboard

### PR DESCRIPTION
**Pull request by shankari**
After doing the heavy lifting for implementing
https://github.com/e-mission/e-mission-docs/issues/476
this is actually super simple

- Switch to reading confirmed_trips instead of cleaned_trips
- This leads to a table with user_inputXXX for each user input XXX
    - Remove the user input prefix

We now end up with a table with the user inputs as columns.
Et Voila!

Please see screenshots in PR

This doesn't fully solve the problem of how to determine whether trips have
been confirmed or not, but that will require some careful design to be sufficiently general.
I will open an issue for that and send a separate PR.

### CODE REVIEW

**Comment by shankari** [comment]
Screen Shot 2020-12-18 at 11 30 29 AM

**Comment by shankari** [comment]
Screen Shot 2020-12-18 at 11 35 08 AM

**Comment by shankari** [comment]
In the eBike project, which has three inputs, the third input shows up automatically (data redacted for obvious reasons).

Screen Shot 2020-12-18 at 4 39 58 PM

**Comment by asiripanich** [comment]
Thanks Shankari for the PR. For some weird reasons, again, all the checks have failed. I will resolve them and merge this soon.

**Comment by asiripanich** [comment]
The PR looks good. I'm going to merge it and ignore the errors on the Ubuntu checks. I think those are not an issue related to the changes you made. Will fix the CI in another PR #30.

**Pull request merged**
