### PR TITLE
Load trips based on ndocs

### PR DESCRIPTION
**Pull request by allenmichael099**
This branch bases trip loading and location loading on the number of documents in the date range and the specified max documents per trip found in config-default.yml.

The logic for whether trips or locations can be loaded is:
- trips <= max_documents: load them
- trips > max_documents: warn user

when the user presses the "get trajectories" button:
- If trips for the given date range have already been loaded:
  - trips + trajectories <= max_documents: get all locations
  - else trips + min_locations_per_trip * trips <= max_documents: get sample of locations
  - else trips + min_locations_per_trip * trips > max_documents: warn user that we can't do this

Locations and trajectories do not get loaded until the user clicks get trajectories and the number of documents is reasonable. 

The 'Separately load locations' commit covers most changes:

- trips no longer load on startup
- added max_documents_for_mod_load_trips and min_locations_per_trip to  the YAML config
- ran devtools::document()
- made mod_load_locations
  - this specifies behavior for the map with the get trajectories button
- renamed reload data button in mod_load_trips
- in app_server, added checks for data_geogr$trips
- data_geogr gets updated by mod_load_locations_server

In utils_query_database:
- added downsample_cleaned_locations_by_timestamp function
- (currently not in use) added query_most_recent_n_trips_docs function
- refactored some query strings with  sprintf

### CODE REVIEW

**Comment by allenmichael099** [comment]
I still need to do further tests with the larger dataset.

**Comment by allenmichael099** [comment]
So far it appears to be working properly on the January data, handling each of the three cases for the locations and the two for trips.

**Comment by shankari** [comment]
I will attempt to deploy this over the weekend to test it out and then we can merge.

**Comment by shankari** [comment]
It's interesting that you chose to use the aggregate throughout.
Some of these have equivalents using more standard mongodb commands - e.g. to find the last n, I typically use

```
.find({}).sort("data.end_ts", -1).limit(1)
```

The aggregate is also fine! This is just for FYI

**Comment by asiripanich** [comment]
@allenmichael099 Let's load 7 days of trips in the first launch.

**Comment by shankari** [comment]
Can we put this into the config options so it is easy to change for individual deployments? Then, if we know we are going to have ~ 10 people, we can load a month at a time.

**Comment by allenmichael099** [comment]
@shankari Unfortunately I couldn't reproduce your error. I was able to load trips for the entire date range, and trajectories for at least a month of data using the Stage July 19 data. Got any suggestions to try to replicate it? I will now fix up the duplicate supplementary tables problem. Maybe it has to do with some interaction with Editable bike check in.

**Comment by shankari** [comment]
This might then be because of two issues:
- R running in ubuntu docker, OR
- the memory limit

Let me pull your current changes and retry

**Comment by shankari** [comment]
@allenmichael099 did you try from my branch? I wonder there was some error in the way I resolved the merge conflicts?

**Comment by allenmichael099** [comment]
@shankari I just tried from your branch- it seems to be working fine. :( Yesterday's error will be hard to find and fix.

**Comment by asiripanich** [comment]
@allenmichael099 could you please update from master and solve all merge conflicts before I merge ? Thanks!

**Comment by shankari** [comment]
For the record, if the dashboard memory size is set to 1GB, 
setting the ` max_documents_for_mod_load_trips` to 10k is too large. 75k seems to work.

**Pull request merged**
