### PR TITLE
Display the inferred labels correctly

### LINKED ISSUE #69: Serialize JSON in the trips table
As part of the auto-labeling functionality, we added the set of automatically inferred labels to each confirmed trip object. These labels are a JSON dict `[{labels: {mode_confirm: X, replace_confirm: Y}, p: <probability>}]`, similar to 

```
[{'labels': {'mode_confirm': 'bike',
   'purpose_confirm': 'exercise',
   'replaced_mode': 'shared_ride'},
  'p': 0.5},
 {'labels': {'mode_confirm': 'bike',
   'purpose_confirm': 'home',
   'replaced_mode': 'shared_ride'},
  'p': 0.5}]
```

These show up automatically in the data table, but because this is a JSON array, they show up as `[(object Object), (object Object)]` (see screenshot). Would it be possible to `JSON.serialize` this field so the deployer can get a sense of what the trip might be even if the user hasn't labeled it? I think @allenmichael099 had an example of applying a javascript transform to a column (for the bike checkinout table).

image001

### PR DESCRIPTION
**Pull request by shankari**
This fixes https://github.com/asiripanich/emdash/issues/69

It basically changes the rendering for the inferred trips table to JSON stringify the array,
similar to https://github.com/asiripanich/emdash/commit/eb7921f1

This change works (see screenshots).
However, it has some hacks that should be cleaned up by somebody with more R knowledge than me.

- Multiple copies of `datatable_options`

The current codebase has two identical copies of `datatable_options`
https://github.com/asiripanich/emdash/blob/5334c9229febaddaa234a3d1adc62f8f90547a90/R/app_server.R#L167
and
https://github.com/asiripanich/emdash/blob/5334c9229febaddaa234a3d1adc62f8f90547a90/R/app_server.R#L195

To be consistent with the existing codebase, I have created a third copy for the trips object.
In the long-term, we need to unify all of these to ensure DRY

- Hardcoded column for `inferred_trips`

The `inferred_trips` column number is currently hard-coded to 5. This is because, due to removed columns before display,

```
inferred_label_index <- which(names(data_geogr$trips) == "inferred_labels")
```
returns 17.

We need to find the index in the list of _displayed_ columns, but I don't
understand R well enough to understand where and how to make that change.

@asiripanich, could you clean up the hacks, or do you want to merge first?

### CODE REVIEW

**Comment by shankari** [comment]
## Before 
Screen Shot 2021-09-14 at 9 56 56 AM 

## After
Screen Shot 2021-09-14 at 1 39 35 PM

**Comment by asiripanich** [comment]
Thanks @shankari, can you also send me a test database to run?

**Comment by shankari** [comment]
@asiripanich here you go! The result should look like this

Screen Shot 2021-09-15 at 1 35 54 PM

**Comment by shankari** [comment]
@asiripanich you fixed the first issue (unifying the `datatable_options`) but I don't think you fixed the second issue (hardcoding `inferred_labels` because some columns are removed before display). Any thoughts on how to fix that?

**Comment by asiripanich** [comment]
@shankari noted. Will take a look and let you know.

**Pull request merged**
